### ISSUE TITLE
Catkin_make returning errors

### ISSUE THREAD

**Issue by petherman** [chrisl8/ArloBot#16]
I am receiving 'could not find a package configuration file provided by "PACKAGE_NAME" with any of the the following names' errors.

I am using Ubuntu 14.04 LTS on VMWare Workstation 12 Pro and ROS Indigo.

I have tried manually installing the packages but eventually i get to a package called "ceres" and can't progress any further.

I have also tried removing and reinstalling ROS Indigo and have not seen any results.

https://snag.gy/H4eEvW.jpg

**Comment by chrisl8** [comment]
Sorry, I am at a loss here.

Do you get these errors when you just go through the ROS Install setup here:
http://wiki.ros.org/indigo/Installation/Ubuntu

Also, I'm moving to Kinetic on Ubutu 16.04, which is now the default branch.
Maybe you could try that?

**Comment by chrisl8** [comment]
The solution is to add two more packages before running the install or cmake:

```
    sudo apt install ros-kinetic-geodesy 
    sudo apt install libceres-dev
```

I will go ahead and add those two packages to the install now.
