### ISSUE TITLE
Quickstart board importance

### ISSUE THREAD

**Issue by DinoJukic** [chrisl8/ArloBot#17]
Greetings,

I was wondering if the quickstart board mentioned in the installation guide is necessary? When I try to run the  ./start-arlobot-only.sh or ./start-robot.sh script I get an error saying there is no quickstart board connected. 

Is there a way for me to make the script ignore this, since I don't have a quickstart board?

Kind regards.

**Comment by chrisl8** [comment]
Sorry for the late reply. I'm not sure why it took me so long to see this.

If you edit ~/.arlobot/personalDataForBehavior.json

and change "hasQuickStartBoard": true, to "hasQuickStartBoard": false,

it should fix that.

Although I'm not sure why it was set to true.

If that doesn't fix it, then the error is in the file:
https://github.com/chrisl8/ArloBot/blob/kinetic/scripts/check_hardware.sh
or on your system:
~/catkin_ws/src/ArloBot/scripts/check_hardware.sh

Where hopefully you can fix it. :)
