### ISSUE TITLE
flash Melodic version of Arlobot C code with Simple IDE fails with '_fdserial_rxCount' 

### ISSUE THREAD

**Issue by sunglyoungKim** [chrisl8/ArloBot#171]
I am trying to flash new Arlobot code that is provided by chrisl8 from melodic branch.
When I build ROSinterfaceForArloBot.C by SimpleIDE I got the build Failed and get this message : Check source for bad function call or global variable name '_fdserial_rxCount'
It seems like I need more library file tha arlodrive or related dhb_10 library. 

This is the whole message from Simple IDE

Project Directory: /home/sk/catkin_ws/src/ArloBot/PropellerCodeForArloBot/

SimpleIDE Version 1.0.1
/home/sk/Documents/SimpleIDE/Learn/Simple Libraries/
/home/sk/Documents/SimpleIDE/ Updated on: 2021-09-07

propeller-elf-gcc -v GCC 4.6.1 (propellergcc_v1_0_0_2411)
propeller-elf-gcc -I . -L . -I../../../../.arlobot/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Text Devices/libfdserial -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Text Devices/libfdserial/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Text Devices/libsimpletext -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Text Devices/libsimpletext/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Utility/libsimpletools/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Protocol/libsimplei2c/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Sensor/libping -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Sensor/libping/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Convert/libadcDCpropab -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Convert/libadcDCpropab/cmm/ -I /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Robotics/Arlo/libarlodrive -L /home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Robotics/Arlo/libarlodrive/cmm/ -o cmm/ROSInterfaceForArloBot.elf -Os -mcmm -m32bit-doubles -fno-exceptions -std=c99 -ffunction-sections -fdata-sections -Wl,--gc-sections ROSInterfaceForArloBot.c -lm -lfdserial -lsimpletext -lsimpletools -lsimplei2c -lping -ladcDCpropab -larlodrive -lm -lfdserial -lsimpletext -lsimpletools -lsimplei2c -lping -ladcDCpropab -lm -lfdserial -lsimpletext -lsimpletools -lsimplei2c -lping -lm -lfdserial -lsimpletext -lsimpletools -lsimplei2c -lm -lfdserial -lsimpletext -lsimpletools -lm -lfdserial -lsimpletext -lm -lfdserial -lm
In file included from ROSInterfaceForArloBot.c:35:0:
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: excess elements in array initializer [enabled by default]
../../../../.arlobot/per_robot_settings_for_propeller_c_code.h:131:5: warning: (near initialization for 'IRstartSlowDownDistance') [enabled by default]
ROSInterfaceForArloBot.c:153:1: warning: excess elements in array initializer [enabled by default]
ROSInterfaceForArloBot.c:153:1: warning: (near initialization for 'irArray') [enabled by default]
/home/sk/Documents/SimpleIDE/Learn/Simple Libraries/Robotics/Arlo/libarlodrive/cmm//libarlodrive.a(drive_config.o): In function `_dhb10_com':
(.text+0x58): undefined reference to `_fdserial_rxCount'
collect2: ld returned 1 exit status
Done. Build Failed!

Check source for bad function call or global variable name `_fdserial_rxCount'

Please let me know how I can solve this problem

Thank you

**Comment by chrisl8** [comment]
I haven't used SimpleIDE in a while now, because Parallax does not provide a working version for Linux. Instead this version of the system uses PropWare.

If you ran the setup script to install this, then the only thing you need to do after editing the .h files is run the script `install_Propeller_code.sh` from the scripts folder to automatically install the required code to your Propeller Activity Board.

This page should explain the use of PropWare if you want more details:  
https://ekpyroticfrood.net/?p=551

Please let me know if this helps or not.

P.S. Be sure that you did edit `per_robot_settings_for_propeller_c_code.h` to set the specifics for your setup, and that you didn't create any errors in that code file. Based on the error, it could be that you have a mismatch between the array count variable and the actual array length?

**Comment by sunglyoungKim** [comment]
Thank you for replying my questions.

May I know how I can check the actual array length and number of the array count variable?

Also, it could be a problem if I didn't update dhb_10 firmware? I am not sure current dhb_10 firmware version and whether it's the newest one or not.

Thank you

**Comment by sunglyoungKim** [comment]
> I haven't used SimpleIDE in a while now, because Parallax does not provide a working version for Linux. Instead this version of the system uses PropWare.
> 
> If you ran the setup script to install this, then the only thing you need to do after editing the .h files is run the script `install_Propeller_code.sh` from the scripts folder to automatically install the required code to your Propeller Activity Board.
> 
> This page should explain the use of PropWare if you want more details:
> https://ekpyroticfrood.net/?p=551
> 
> Please let me know if this helps or not.
> 
> P.S. Be sure that you did edit `per_robot_settings_for_propeller_c_code.h` to set the specifics for your setup, and that you didn't create any errors in that code file. Based on the error, it could be that you have a mismatch between the array count variable and the actual array length?

And also, I think you are confused with noetic and melodic version. There is no install_propeller_code.sh in melodic branch. Can I use the code in melodic, too?

Thank you

**Comment by sunglyoungKim** [comment]
Using PropeWare and noetic version of code works fine in Melodic. however, my Arlobot motor still doesn't move by sending signal using keyboard_teleop.launch

**Comment by chrisl8** [comment]
Oh, I'm so sorry, you said Melodic, but I forgot that Noetic is the current version. These run together in my mind.

Have you tried running `~/catkin_ws/src/ArloBot/scripts/PropellerSerialTest.sh` from your  system that is connected to the Propeller board? It should help you debug the connection and see in real time what is happening.

**Comment by sunglyoungKim** [comment]
The output of PropellerSerialTest.sh is 
o: (0.36xx,  0.0033249xxx, 1.0, 0, 0, 0, 0) 
The first two numbers are modified and plugged in part has been modified through the setting, too

There is no i: init request recevied

So it means the board only talks to my laptop but doesn't receive my input?

**Comment by sunglyoungKim** [comment]
I didn't have permission to open the Serial port on my laptop. Now it works. Thank you!
