### ISSUE TITLE
Replace obsolete DHB-10 with RoboClaw Motor Controller

### ISSUE THREAD

**Issue by TCIII** [chrisl8/ArloBot#176]
@chrisl8,

To help prevent the Arlobot robot chassis from collecting dust in some corner of an experimenter's workshop, how about replacing the DHB-10 with a RoboClaw Motor Controller?

There are a number of ROS Nodes written for the RoboClaw Motor Controller and the Basic Micro website has Python control programs available for the Raspberry Pi SBC as well as C++ programs too.

I have the time and resources available to help support such an effort.

Regards,
TCIII

**Comment by chrisl8** [comment]
@TCIII The first issue is the hardware.

 - It **may** be possible to operate the current car door window motors with a Roboclaw, but ideally we would use something "off the shelf" that also has good encoders built in.
   - I have been making use of these motors from Pololu for other projects: https://www.pololu.com/category/116/37d-metal-gearmotors and they work great, but I'm not sure how to tell if they are capable of dealing with the load of the Arlobot?
   - If we use different motors, then we also have to design and fabricate a method of mounting them to the platform.
 - If we use the same motors, then we need to find out **IF** the Roboclaw can interface with the IR based encoders or not, and **IF and HOW** to drive these motors with a Roboclaw

I do have a couple of Roboclaw controllers, but I don't know when I will get around to attempting to wire up the motors on the Arlobot to it. Since it works "as is" I'm not highly motivated to pull the wiring off of the DHB-10 to experiment with them.

It would be more interesting if we could use different motors, preferably with built in encoders like ones from Pololu, but then the issue of mounting them comes along.

Another option is to just build an entirely different platform from scratch and leave the Arlobot as is.

**Comment by TCIII** [comment]
@chrisl8, 

> * I have been making use of these motors from Pololu for other projects: https://www.pololu.com/category/116/37d-metal-gearmotors and they work great, but I'm not sure how to tell if they are capable of dealing with the load of the Arlobot?

I have used that [motor/encoder](https://www.pololu.com/product/4756) combination on a medium weight robot using a robot chassis like [this](https://www.zagrosrobotics.com/shop/item.aspx?itemid=521). I am using the Donkey Car "path_follow" template from the [921 branch](https://github.com/autorope/donkeycar/tree/921-next-generation-odometer-parts). Presently the robot can use either wheel encoders or the Intel T265 Tracking Camera to record a path and then drive the recorded path. There is no training involved other than driving the path just once. We hope to fuse the wheel encoders data with the T265 data to create a very reliable path follower.

The Pololu motor/encoder combination will not support the weight of a Arlo size robot chassis. I use two 3S 5000 mahr LiPos to power the robot I described above to help keep the chassis weight down. The onboard SBC is a Nano 4GB and controls a Dimension Engineering Sabertooth 2x5RC Motor Controller (Differential Drive Mode) through a PCA9685 Servo Controller.

Also the Pololu motor/encoder uses a phosphor/bronze Oilite sleeve bearing that will not support the loads that the Parallax motor/wheel combination can support. I prefer [geared motors](https://www.servocity.com/5202-series-yellow-jacket-planetary-gear-motor-99-5-1-ratio-60-rpm-3-3-5v-encoder/) with a ball bearing supporting the output shaft.

I think that we might have to abandon the Arlo chassis in favor of the robot chassis I mentioned above. It is reasonable in price, comes in either a square or round configuration, and is stackable like the Arlo chassis.

The pictures below show the robot chassis with a Rpi 4B/4GB and non-encoded motors. The Rpi was replaced with a Nano 4GB and the motors were upgraded to [motors with encoders](https://www.pololu.com/product/4756). Also the T265 is now mounted on a heatsink attached to a shock mount plate and looks straight ahead now.

Comments?



![Latest Robot Pics 001](https://user-images.githubusercontent.com/1240348/148237936-cd5bc38e-2bd9-4b2a-9f69-3aae48da32d3.jpg)
![Latest Robot Pics 002](https://user-images.githubusercontent.com/1240348/148237975-105daed6-4a7d-4bb0-a8b2-647aba824fef.jpg)

**Comment by TCIII** [comment]
@chrisl8,

I used this [Pololu motor bracket](https://www.pololu.com/product/1995) to mount the Pololu 37D motors in your link above.

I mounted the motor bracket to the end of a 1/4 inch thick piece of rectangular Acrylic which I then mounted to the bottom of the robot chassis.

This motor bracket is much stronger that the [stamped version](https://www.pololu.com/product/1084).

Here is a parts list for a 2WD chassis similar to the Arlo chassis that uses Servo City motor/encoders, but would require some cutting of the bottom plate to clear the wheels as in the Arlo chassis:

- [Motor with encoder](https://www.servocity.com/5202-series-yellow-jacket-planetary-gear-motor-99-5-1-ratio-60-rpm-3-3-5v-encoder/) $39.95 each
- 1206 Series [Pattern Adaptor](https://www.servocity.com/1206-series-pattern-adaptor-16-1/) (16-1) $4.99 each
- 2800 Series Zinc-Plated Steel [Socket Head Screw](https://www.servocity.com/2800-series-zinc-plated-steel-socket-head-screw-m4-x-0-7mm-10mm-length-25-pack/) (M4 x 0.7mm, 10mm Length) $3.39/25 pack
- [U-Channel ](https://www.servocity.com/3-00-aluminum-channel/)(3 Hole, 3.00" Length) $3.99 each
- 6mm to 6mm [Set Screw Shaft Coupler](https://www.servocity.com/6mm-to-6mm-set-screw-shaft-coupler/) $4.99 each
- 2101 Series [Stainless Steel D-Shaft](https://www.servocity.com/2101-series-stainless-steel-d-shaft-6mm-diameter-40mm-length/) (6mm Diameter, 40mm Length) $1.59 each
- 1601 Series [Flanged Ball Bearing](https://www.servocity.com/6mm-id-x-12mm-od-flanged-ball-bearing-2-pack/) $3.39/2 pack
- 6mm Bore, [12mm Hex Wheel Mount](https://www.servocity.com/6mm-bore-12mm-hex-wheel-mount/) $7.99/2 pack
- [5.4 inch dia Tires](https://www.servocity.com/5-4-off-road-robot-tires-2-pack/) $15.99/2 pack
- [Rims](https://www.servocity.com/revolver-robot-wheels-2-pack/) for the 5.4 inch dia Tires $5.99/2 pack
Alternate wheel and wheel adapters:
- Pololu Aluminum Scooter [Wheel Adapter](https://www.pololu.com/product/2674) for 6mm Shaft $4.95 each
- Scooter/Skate [Wheel](https://www.pololu.com/product/3281) 144×29mm - Black $7.95 each
- Scooter/Skate [Wheel](https://www.pololu.com/product/3283) 200×30mm - Black $12.95 each
- Chassis Base: [16 in X 16 in square](https://www.zagrosrobotics.com/shop/item.aspx?itemid=518) or [16 in round](https://www.zagrosrobotics.com/shop/item.aspx?itemid=607)

The motor/encoder/wheel/mounting hardware assemblies works out to about $150 total for both pairs, plus shipping, which is quite a bit less than a pair of the Parallax motor/wheel assemblies plus the quadrature encoders are of much higher resolution than the Parallax quadrature encoders.

Arguably the wheels do not have innertubes and the rims are plastic versus the Parallax aluminum rims, but the price is very attractive. However these tires will extend a little over an inch outside of the recommended 16 inch diameter chassis.

The alternate scooter wheels and wheel adapters will up the total cost slightly, but will keep the wheels within the 16 inch diameter of the recommended chassis base. Though the scooter wheels might not have as good of traction as the off road robot tires.

Comments?

Regards,
TCIII

**Comment by TCIII** [comment]
@chrisl8,

Have you seen this [issue](https://github.com/sonyccd/roboclaw_ros/issues/27) concerning the RoboClaw ROS Node?

Question:
Do you really need a robot chassis as big as Arlo?

Answer:
Maybe not. 
How about using a 14 inch diameter ABS chassis like this [one](https://www.zagrosrobotics.com/shop/item.aspx?itemid=850)
Then the following Motor/Wheel configuration:
1) [Motor with encoder](https://www.pololu.com/product/4756)
2) [Motor mount](https://www.pololu.com/product/1995)
3) [Scooter wheel adapter](https://www.pololu.com/product/2674)
4) [Scooter wheel](https://www.pololu.com/product/3281)

There will be a minimum wheel offset using the scooter wheels/adapters that will significantly reduce the offset loading on the D37 motor driveshaft bearing.

Using a RoboClaw 2X7 Motor Controller and possibly an Arduino Mega 2560 to take the place of the PAB for motor control and sensor monitoring might be the way to go?

TCIII

**Comment by TCIII** [comment]
@chrisl8,

 Parallax has a [Universal Motor Driver](https://www.parallax.com/product/universal-motor-driver-p2-add-on-board/?mc_cid=5286e7b7fb&mc_eid=a5785c4895) that will work with all versions of the P2.

This motor driver might be an alternate to use in place of a RoboClaw motor controller when building an "off the shelf" ArloBot?

The price is about the same as the 2x7 RoboClaw, but will handle 20 amps/side and you could still use P1/P2 software by updating to a P2.

Comments?

TCIII

**Comment by TCIII** [comment]
@chrisl8,

Have you made any progress in replacing the Parallax DHB-10 Motor Controller with a RoboClaw Motor Controller?

Regards,
TCIII

**Comment by chrisl8** [comment]
As much as I hate to admit it, I have other priorities and this is not likely to happen. Maybe someday when I retire I can return to this or maybe someone will hire me full time as an "open-source robotic platform maintainer", but until then I am going to shelve this.
