### ISSUE TITLE
Are you available to tutor?

### ISSUE THREAD

**Issue by electricmovementdan** [chrisl8/ArloBot#2]
The ROS documentation is so lacking and I'm trying to get up to speed as quickly as possible. Are you willing to tutor me in getting started? I would be thrilled to be able to accomplish what you demonstrated in your arlobot video. I would be happy to compensate you for your time.

You can reach me at dan <at> electricmovement.com

**Comment by chrisl8** [comment]
I already answered this via email, but for future onlookers.
No, I don't have time to tutor, although I do carry on regular email correspondence with several people who are building ArloBot. I can answer any questions here or in email.

If you want to learn ROS, better than I know it, I suggest the ROS by Example books: http://www.pirobot.org/
