### ISSUE TITLE
/dev/fd/63: line 693: npm: command not found

### ISSUE THREAD

**Issue by akycdi** [chrisl8/ArloBot#207]
I am getting this error while installing the ros on ubuntu in VM.
I have installed the ros noetic version in ubuntu 20.04
![image](https://user-images.githubusercontent.com/84339290/183634899-7b69054a-5de3-4911-94a5-6783cf898b77.png)

**Comment by akycdi** [comment]
presented with another error

**Comment by chrisl8** [comment]
Did you get it sorted?

**Comment by akycdi** [comment]
Yes, I have sorted but unfortunately i am unable to run the arlo on the both ubuntu 20.04 and 18lts versions 
I am getting the same error i have changed the noetic and the  melodic visa versa
Sorry for the late reply and can you help me with this error.

i am just trying to run the script.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84339290/185921267-08b28b6a-766d-4203-88a3-a8abf5615539.png)

**Comment by chrisl8** [comment]
It seems to be having trouble finding `simpleide` which doesn't surprise me as that is basically deprecated by the creator. The most recent version uses another method of installing. In fact `setup-noetic.sh` doesn't ever try to run simpleide.

Can you try `setup-noetic.sh` again and let me know if it is still giving you errors?

**Comment by chrisl8** [comment]
Closing due to lack of response for a while. If you are still having trouble feel free to reopen this issue.

**Comment by akycdi** [comment]
Yes, Thanks I have completed the project with the SimpleIDE . I haven't been on Git that much and I don't know how the notification got missed. Thanks again for the reply.
